kind: pipeline
type: docker
name: sonar-pr-main

steps:
  - name: auto-tag
    image: alpine:latest
    environment:
      GIT_USERNAME: ""
      GIT_PASSWORD: ""
    secrets:
      - source: GIT_USERNAME
        target: GIT_USERNAME
      - source: GIT_PASSWORD
        target: GIT_PASSWORD
    commands:
      - echo "REAL CHECK"
      - echo "USERNAME from env: $GIT_USERNAME"
      - echo "PASSWORD from env: ${#GIT_PASSWORD} characters long"
      - export REMOTE_URL="https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/jeremycho-eq4all/cicd.git"
      - echo "REMOTE_URL is: $REMOTE_URL"
      - apk add --no-cache git
      - git config --global user.email "droneci@eq4all.co.kr"
      - git config --global user.name "drone"
      - git remote set-url origin "$REMOTE_URL"
      - VERSION=$(date +%Y.%m.%d.%H%M)
      - git tag -a "v${VERSION}" -m "Auto tag by Drone"
      - git push origin "v${VERSION}"

  # - name: skip-non-main-pr
  #   image: alpine
  #   commands:
  #     - |
  #       echo "Target branch: $DRONE_TARGET_BRANCH"
  #       if [ "$DRONE_TARGET_BRANCH" != "main" ]; then
  #         echo "⏭️ Not a PR to main. Skipping pipeline..."
  #         exit 78
  #       fi

  # - name: test & coverage
  #   image: python:3.11
  #   commands:
  #     - pip install -r requirements.txt
  #     - pytest --cov=. --cov-report=xml

  # - name: sonar scan
  #   image: sonarsource/sonar-scanner-cli
  #   environment:
  #     SONAR_TOKEN:
  #       from_secret: sonar_token
  #   commands:
  #     - sonar-scanner -Dsonar.projectKey=cicd -Dsonar.sources=. -Dsonar.host.url=http://192.168.1.250:7895 -Dsonar.login=$SONAR_TOKEN -Dsonar.python.coverage.reportPaths=coverage.xml -Dsonar.working.directory=/tmp/.scannerwork

  # - name: quality gate check
  #   image: curlimages/curl
  #   environment:
  #     SONAR_TOKEN:
  #       from_secret: sonar_token
  #   commands:
  #     - >
  #       curl -s -u $SONAR_TOKEN: "http://192.168.1.250:7895/api/qualitygates/project_status?projectKey=cicd" | tee /tmp/result.json | grep -q '"status":"ERROR"' && exit 1 || exit 0